[flake8]
max-line-length = 100
max-complexity = 10
copyright-check = True
copyright-author = Canonical Ltd.

[tox]
skipsdist = True

[testenv]
setenv =
    PYTHONPATH={toxinidir}/src:{toxinidir}/lib
deps =
    -rrequirements.txt
    -r test-requirements.txt

[testenv:lint]
deps =
    flake8
    flake8-copyright<0.3
    black
commands =
    flake8 {toxinidir}/src {toxinidir}/tests
    black --check --diff {toxinidir}/src {toxinidir}/tests

[testenv:unit]
commands =
    pytest -vv --show-capture=no --log-cli-level=INFO {toxinidir}/tests/unit

[testenv:integration]
deps =
    {[testenv]deps}
    -r test-integration-requirements.txt
# _no_trust failing in github runner, possibly because it starts before previous charm is torn down?  Works in isolation locally
commands =
    pytest -vv --show-capture=no --log-cli-level=INFO -s {posargs} {toxinidir}/tests/integration --ignore=tests/integration/test_charm_no_trust.py
